local function playCutscene()
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local player = Players.LocalPlayer
-- Variables

-- RemoteEvent
local REReplicateCutscene = ReplicatedStorage.Packages._Index["sleitnick_net@0.2.0"].net["RE/ReplicateCutscene"]

-- Fungsi trigger cutscene
local function cs(position)
task.wait(3.2)
    firesignal(REReplicateCutscene.OnClientEvent,
        "Skeleton Narwhal",          -- rarity / tier
        player,            -- target: LocalPlayer
        position,          -- posisi offset
        "Bandit Angelfish",       -- identifier
        {
            Weight = 13503.5
        }
    )
task.wait(1.8)
 firesignal(REReplicateCutscene.OnClientEvent,
        "SECRET",          -- rarity / tier
        player,            -- target: LocalPlayer
        position,          -- posisi offset
        "Bandit Angelfish",       -- identifier
        {
            Weight = 13503.5
        }
    )
end
local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_net@0.2.0"].net["RF/RequestFishingMinigameStarted"]
local oldRequest
oldRequest = hookmetamethod(game,"__namecall",function(self,...)
local method = getnamecallmethod()
if method == "InvokeServer" and rawequal(self,Event) then
task.spawn(function() 
local character = player.Character or player.CharacterAdded:Wait()
local root = character:WaitForChild("HumanoidRootPart")
 local center = root.Position + Vector3.new(0, -10, 0) 
 local cspos = center + (root.CFrame.LookVector * 25)
cs(cspos)
end)
end
return oldRequest(self,...)
end)
end
local function b()
    -- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_net@0.2.0"].net["RE/ObtainedNewFishNotification"]
for _, Connection in getconnections(Event.OnClientEvent) do
    local old; old = hookfunction(Connection.Function, function(...)
        task.wait(6.3)
        return old(...)
    end)
end
end
local function C()
local items = game:GetService("ReplicatedStorage").Items
local var = {"Ancient Arapaima", "Abyshorn Fish", "Drippy Tucanare", "Sail Fish", "Water Snake", "Thinkler Fish","Sophisticated Angler", "Red Goatfish", "Zebra Snakehead"}
for i,v in ipairs(var) do
local varEdit = require(items[v])
local data = varEdit.Data
data.Tier = 1000
data.Description = "Epstein files that went missing a long time ago\nFrom: Jeffrey Epstein"
data.Icon = getcustomasset("epstein file.png")
data.Type = "Enchant Stones"
data.Name = "Ijazah Asli J███ W█████"
varEdit.Probability.Chance = 1 / math.huge
end
end

local function R()
local player = game:GetService("Players").LocalPlayer
local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_net@0.2.0"].net["RE/ReplicateTextEffect"]
for i , v in ipairs (getconnections(Event.OnClientEvent)) do
local oldExclaim
oldExclaim = hookfunction(v.Function,function(self,args)
local head = player.Character:WaitForChild("Head", 1)
if self.Container == head then
self = {
        UUID = "6fd3c416-3616-44ae-a7a5-7bc698c6e8df",
        Channel = "All",
        TextData = {
            AttachTo = game:GetService("Players").LocalPlayer.Character.Head,
            Text = "!",
            EffectType = "Exclaim",
            TextColor = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.new(0.06470589637756, 1, 0.83333334326744)),
                ColorSequenceKeypoint.new(1, Color3.new(0.06470589637756, 1, 0.73333334326744))
            })
        },
        Duration = 0.5,
        Container = game:GetService("Players").LocalPlayer.Character.Head
    }
end
return oldExclaim(self)
end)
end
end
local function m()
-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt
local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_net@0.2.0"].net["RE/DisplaySystemMessage"]
firesignal(Event.OnClientEvent, 
    "<b><font size=\"18\">[Server]:</font></b> permensuguss222 obtained a <b><font color=\"rgb(179, 115, 248)\">Fangtooth (162kg)</font></b> with a 1 in 2K chance!",
    nil
)
firesignal(Event.OnClientEvent, 
    "<b><font size=\"18\">[Server]:</font></b> Udin Sedunia obtained a <b><font color=\"rgb(179, 115, 248)\">Fangtooth (158.8kg)</font></b> with a 1 in 2K chance!",
    nil
)
firesignal(Event.OnClientEvent, 
    "<b><font size=\"18\">[Server]:</font></b> Ucup5454K obtained a <b><font color=\"rgb(179, 115, 248)\">Fangtooth (164kg)</font></b> with a 1 in 2K chance!",
    nil
)

end
local function NF()
local TextChatService = game:GetService("TextChatService")
local Event = game:GetService("ReplicatedStorage").Packages._Index["sleitnick_net@0.2.0"].net["RE/FishCaught"]
local function sendm(vars)
local msg = `<b><font size=\"18\">[Server]:</font></b> CecepHermanos obtained a <b><font color=\"rgb(24, 255, 152)\">Ijazah Asli J███ W█████ ({vars}kg)</font></b> with a 1 in infNVD chance!`
local channel = TextChatService:WaitForChild("TextChannels"):WaitForChild("RBXGeneral")
channel:DisplaySystemMessage(msg)
end
for i,v in ipairs (getconnections(Event.OnClientEvent)) do
local hf
hf = hookfunction(v.Function,function(self,args)
sendm(args.Weight)
return hf(self,args)
end)
end
end
task.spawn(fucntion()
    m()
end)
task.spawn(fucntion()
    R()
end)
task.spawn(fucntion()
    C()
end)
task.spawn(fucntion()
    b()
end)
task.spawn(function()
NF()
end)


playCutscene()
